name: aqualotl
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cloud_firestore:
  firebase_core:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  get: ## ~icons~

  line_awesome_flutter: ^2.0.0
  cupertino_icons: ^1.0.2

  animations: ^2.0.7
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.1.1
  sleek_circular_slider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: TiltNeon
      fonts:
        - asset: fonts/TiltNeon-Regular-VariableFont_XROT,YROT.ttf
    - family: Righteous
      fonts:
        - asset: fonts/Righteous-Regular.ttf
    - family: TiltWarp
      fonts:
        - asset: fonts/TiltWarp-Regular-VariableFont_XROT,YROT.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
